### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by Luhyy** [MichaelBosello/f1tenth-RL#1]
Hello friends，I am a master's student from China. By chance, I saw a video you posted on youtube,and I came to your github homepage.My research topic is also related to autonomous driving.I admire your scientific research ability and I am very grateful for your project.However I can 't download your paper.I would be very grateful if you could send me a paper.  hbw1170898865@163.com

**Comment by MichaelBosello** [comment]
https://www.researchgate.net/publication/358517210_Train_in_Austria_Race_in_Montecarlo_Generalized_RL_for_Cross-Track_F1_tenth_LIDAR-Based_Races
