### ISSUE TITLE
Model not reloadable after certain number of training steps

### ISSUE THREAD

**Issue by YLJMYZH** [MichaelBosello/f1tenth-RL#2]
## Description

I have encountered an issue where the trained model cannot be reloaded after a certain number of training steps.

## Background

I am an undergraduate student from China studying reinforcement learning using your paper and code. However, I encountered the issue mentioned above.

## Steps to Reproduce

1. Train the model.
2. Attempt to reload the trained model.
3. Observe that the model fails to load.

## Expected Behavior

The trained model should be reloadable regardless of the number of training steps.

## Actual Behavior

After training for a certain number of steps, the model cannot be reloaded, but non error is encountered.

## System Information

- ROS1 Melodic (desktop-full)
- conda 24.1.2 (Python version: Python 3.7)
- VMware® Workstation 17 Pro version: 17.0.0 build-20800274
- Ubuntu 18.04 LTS
- keras 2.11.0
- tensorflow 2.11.0
- catkin-pkg 1.0.0
- rospkg 1.5.1

## Additional Information

- f1tenth-RL version: git clone https://github.com/MichaelBosello/f1tenth-RL.git

Please let me know if you need any further information to debug this issue. Thank you!

**Comment by MichaelBosello** [comment]
- After how many steps do you face the problem?
- What do you mean you cannot reload the model but no error is encountered?

**Comment by YLJMYZH** [comment]
I trained for nearly 2000 steps and then followed the command given in README.md: `python3 rl_car_driver.py --model=./run-xxx-xxx/models/`. However, it kept repeating:
```
saving...
saved
Episode 0 ended with score: 39.47...
```
But the car doesn't move at all.

**Comment by MichaelBosello** [comment]
I assume you are running on the simulator. Are you using the `--simulator` flag?

**Comment by YLJMYZH** [comment]
Oh, I found my problem. I forgot to add --simulator to python3 rl_car_driver.py --model=./run-xxx-xxx/models/. Thank you.
